---
title: "Spatial Viz"
name: Pablo Jiménez
---

---
execute:
  echo: true
  warning: false
  error: false

format:
  html:
    code-fold: true
---


Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.

```{r}
library(tidyverse)

```

```{r}
library(ggmap) 
library(ggplot2)
library(dplyr)
library(leaflet)
library(sf)
library(rnaturalearth)
library(mosaic)
library(socviz)

data(county_map) 
states_map <- map_data("state")

elections_by_state <-  read.csv("https://mac-stat.github.io/data/election_2020_by_state.csv")
elections_by_counties <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")

ggplot(elections_by_counties, aes(map_id = county_fips, fill = median_rent)) +
  geom_map(map = county_map, color = "black", size = 0.1) + 
  expand_limits(x = county_map$long, y = county_map$lat) +
  theme_map() +
  theme(
    legend.position = "right") +
  coord_equal() +
  scale_fill_gradientn(name = "Median Rent", colors = c("white", "lightgreen", "darkgreen")) +
  labs(
    title = "Median Rent by County",
    caption = "mac-stat.github.io/data/election_2020_county.csv"
  )
```
