---
title: "Exam_2"
format: html
---

# Background

```{r}
library(tidytuesdayR)
library(tidyverse)
library(rnaturalearth)
library(sf)
library(dplyr)
```

```{r}
tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption
view(fc)
```
```{r}
str(fc)
head(fc, 22)
```

# 1. Which are the Countries that consume the most food?

```{r}
total_consumption_by_country <- fc %>%
  group_by(country) %>%
  summarise(total_consumption = sum(consumption)) %>%
  arrange(desc(total_consumption))

print(total_consumption_by_country)
```

# 2. Which top 5 countries consume each food are?

```{r}
top_5_consumers_by_food <- fc %>%
  group_by(food_category) %>%
  arrange(desc(consumption), .by_group = TRUE) %>%
  slice_head(n = 5)

print(top_5_consumers_by_food)
```

# 3 What does the consumption of each food look like?

```{r}
tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption

fcc <- fc %>%
  mutate(country = case_when(
    country == "United States of America" ~ "USA",
    country == "Bosnia and Herz" ~ "Bosnia and Herzegovina",
    country == "Czechia" ~ "Czech Republic",
    country == "Taiwan" ~ "Taiwan. ROC",
    TRUE ~ country
  ))

world <- ne_countries(returnclass = "sf") %>%
  select(name, geometry)

food_consumption_map <- world %>%
  left_join(fcc %>% select(country, consumption, food_category), 
            join_by(name == country)) %>%
  filter(!is.na(consumption)) %>%
  ggplot() +
  geom_sf(aes(fill = consumption)) +
  facet_wrap(~ food_category) +
  scale_fill_viridis_c(option = "plasma", na.value = "lightgray") +
  labs(
    title = "Consumption of Each Food",
    fill = "Consumption"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    strip.text = element_text(size = 10),
    plot.title = element_text(hjust = 0.5)
  )

print(food_consumption_map)
```


